name: AirSonos Test
version: "0.1.0"
slug: airsonos_test
description: Test version to isolate 500 error
url: https://github.com/hansontxn/airsonos-optimized
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: manual
init: false
host_network: true
apparmor: false
options:
  test: true
schema:
  test: bool?