name: AirSonos Optimized
version: "0.3.0"
slug: airsonos_optimized
description: "AirTunes to Sonos devices bridge with HACS optimization"
url: "https://github.com/HansonTan/airsonos-optimized"
codenotary: "notary@home-assistant.io"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
map:
  - "share:rw"
  - "ssl:ro"
  - "config:ro"
options:
  timeout: 5
  verbose: false
  port: 5000
  discovery_timeout: 10
  max_devices: 50
schema:
  timeout: "int(1,300)?"
  verbose: "bool?"
  port: "port?"
  discovery_timeout: "int(1,60)?"
  max_devices: "int(1,100)?"
services:
  - mqtt:need
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
environment:
  LOG_LEVEL: info
  NODE_ENV: production
  DISCOVERY_TIMEOUT: 10
  MAX_DEVICES: 50
audio: true