name: AirSonos Optimized
version: "0.3.1"
slug: airsonos_optimized
description: AirTunes to Sonos devices bridge with Home Assistant integration
url: https://github.com/hansontxn/airsonos-optimized
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
apparmor: false
options:
  timeout: 5
  verbose: false
  port: 5000
schema:
  timeout: int(1,300)?
  verbose: bool?
  port: port?
