name: "AirSonos Simple"
version: "2.0.1"
slug: "airsonos_simple"
description: "Minimal AirSonos implementation"
arch:
  - "amd64"
  - "armv7"
  - "armhf"
  - "aarch64"
  - "i386"
startup: "application"
host_network: true