name: AirSonos Optimized
version: "0.3.0"
slug: airsonos-optimized
description: "AirTunes to Sonos devices bridge with HACS optimization"
url: "https://github.com/hansontxn/airsonos-optimized"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
host_network: true
privilege:
  - NET_ADMIN
  - NET_RAW
options:
  timeout: 5
  verbose: false
  port: 5000
  discovery_timeout: 10
  max_devices: 50
schema:
  timeout: "int(1,300)?"
  verbose: "bool?"
  port: "port?"
  discovery_timeout: "int(1,60)?"
  max_devices: "int(1,100)?"
environment:
  LOG_LEVEL: info
  NODE_ENV: production
  DISCOVERY_TIMEOUT: 10
  MAX_DEVICES: 50