name: "AirSonos Bridge"
version: "1.3.1"
slug: "airsonos_bridge"
description: "AirTunes to Sonos devices bridge"
arch:
  - "amd64"
  - "armv7"
  - "armhf"
  - "aarch64" 
  - "i386"
startup: "application"
host_network: true
options: {}
schema: {}
