name: AirSonos Bridge
version: "1.2.3"
slug: airsonos_bridge
description: AirTunes to Sonos devices bridge with Home Assistant integration
url: https://github.com/hansontxn/airsonos-optimized
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto
init: false
host_network: true
apparmor: false
options:
  timeout: 5
  verbose: false
  port: 5000
  manual_devices: []
schema:
  timeout: int(1,300)?
  verbose: bool?
  port: port?
  manual_devices: "list(match(name=str,ip=str,port=int(1400,65535)?)?)?"
