name: "AirSonos Bridge"
version: "1.2.9"
slug: "airsonos_bridge"
description: "AirTunes to Sonos devices bridge"
arch:
  - "amd64"
  - "armv7"
  - "aarch64"
startup: "application"
host_network: true
options: {}
schema: {}
